[package]
name = "basic_coin"
version = "1.0.0"
authors = []

[addresses]
basic_coin_addr = "18f72db4daaf0760f4717c6ad4ba339967feea5b564fad35613fbc1f505b2300"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
